//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeySAV2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeySAV2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nichts
        ///Duftnote
        ///Niesel
        ///Temposchub
        ///Kampfpanzer
        ///Robustheit
        ///Feuchtigkeit
        ///Flexibilität
        ///Sandschleier
        ///Statik
        ///Voltabsorber
        ///H2O-Absorber
        ///Dösigkeit
        ///Wolke Sieben
        ///Facettenauge
        ///Insomnia
        ///Farbwechsel
        ///Immunität
        ///Feuerfänger
        ///Puderabwehr
        ///Tempomacher
        ///Saugnapf
        ///Bedroher
        ///Wegsperre
        ///Rauhaut
        ///Wunderwache
        ///Schwebe
        ///Sporenwirt
        ///Synchro
        ///Neutraltorso
        ///Innere Kraft
        ///Blitzfänger
        ///Edelmut
        ///Wassertempo
        ///Chlorophyll
        ///Erleuchtung
        ///Fährte
        ///Kraftkoloss
        ///Giftdorn
        ///Konzentrator
        ///Magmapanzer
        ///Aquahülle
        ///Magnetfalle
        ///Lärmschutz
        ///Regengenuss
        ///Sandsturm
        ///Erzwinger
        ///Speck [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Abilities_de {
            get {
                return ResourceManager.GetString("text_Abilities_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None
        ///Stench
        ///Drizzle
        ///Speed Boost
        ///Battle Armor
        ///Sturdy
        ///Damp
        ///Limber
        ///Sand Veil
        ///Static
        ///Volt Absorb
        ///Water Absorb
        ///Oblivious
        ///Cloud Nine
        ///Compound Eyes
        ///Insomnia
        ///Color Change
        ///Immunity
        ///Flash Fire
        ///Shield Dust
        ///Own Tempo
        ///Suction Cups
        ///Intimidate
        ///Shadow Tag
        ///Rough Skin
        ///Wonder Guard
        ///Levitate
        ///Effect Spore
        ///Synchronize
        ///Clear Body
        ///Natural Cure
        ///Lightning Rod
        ///Serene Grace
        ///Swift Swim
        ///Chlorophyll
        ///Illuminate
        ///Trace
        ///Huge Power
        ///Poison Point
        ///Inner Focus
        ///Magma Armor
        ///Water Veil
        ///Magnet Pull
        ///Soundproof
        ///Rain Dish
        ///Sand Stream
        ///Pressure
        ///Thick Fat
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Abilities_en {
            get {
                return ResourceManager.GetString("text_Abilities_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ninguno
        ///Hedor
        ///Llovizna
        ///Impulso
        ///Armadura Batalla
        ///Robustez
        ///Humedad
        ///Flexibilidad
        ///Velo Arena
        ///Elec. Estática
        ///Absorbe Elec
        ///Absorbe Agua
        ///Despiste
        ///Aclimatación
        ///Ojo Compuesto
        ///Insomnio
        ///Cambio Color
        ///Inmunidad
        ///Absorbe Fuego
        ///Polvo Escudo
        ///Ritmo Propio
        ///Ventosas
        ///Intimidación
        ///Sombra Trampa
        ///Piel Tosca
        ///Superguarda
        ///Levitación
        ///Efecto Espora
        ///Sincronía
        ///Cuerpo Puro
        ///Cura Natural
        ///Pararrayos
        ///Dicha
        ///Nado Rápido
        ///Clorofila
        ///Iluminación
        ///Rastro
        ///Potencia
        ///Punto Tóxico
        ///Foco Interno
        ///Escudo Magma
        ///Velo Agua
        ///Imán
        ///Insonorizar
        ///Cura Lluvia
        ///Chorro Are [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Abilities_es {
            get {
                return ResourceManager.GetString("text_Abilities_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun
        ///Puanteur
        ///Crachin
        ///Turbo
        ///Armurbaston
        ///Fermeté
        ///Moiteur
        ///Échauffement
        ///Voile Sable
        ///Statik
        ///Absorb Volt
        ///Absorb Eau
        ///Benêt
        ///Ciel Gris
        ///Œil Composé
        ///Insomnia
        ///Déguisement
        ///Vaccin
        ///Torche
        ///Écran Poudre
        ///Tempo Perso
        ///Ventouse
        ///Intimidation
        ///Marque Ombre
        ///Peau Dure
        ///Garde Mystik
        ///Lévitation
        ///Pose Spore
        ///Synchro
        ///Corps Sain
        ///Médic Nature
        ///Paratonnerre
        ///Sérénité
        ///Glissade
        ///Chlorophylle
        ///Lumiattirance
        ///Calque
        ///Coloforce
        ///Point Poison
        ///Attention
        ///Armumagma
        ///Ignifu-Voile
        ///Magnépiège
        ///Anti-Bruit
        ///Cuvette
        ///Sable Volant
        ///Pression
        ///Isograisse
        ///Matinal
        ///Corps Ar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Abilities_fr {
            get {
                return ResourceManager.GetString("text_Abilities_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niente
        ///Tanfo
        ///Piovischio
        ///Acceleratore
        ///Lottascudo
        ///Vigore
        ///Umidità
        ///Scioltezza
        ///Sabbiavelo
        ///Statico
        ///Assorbivolt
        ///Assorbacqua
        ///Indifferenza
        ///Antimeteo
        ///Insettocchi
        ///Insonnia
        ///Cambiacolore
        ///Immunità
        ///Fuocardore
        ///Polvoscudo
        ///Mente Locale
        ///Ventose
        ///Prepotenza
        ///Pedinombra
        ///Cartavetro
        ///Magidifesa
        ///Levitazione
        ///Spargispora
        ///Sincronismo
        ///Corpochiaro
        ///Alternacura
        ///Parafulmine
        ///Leggiadro
        ///Nuotovelox
        ///Clorofilla
        ///Risplendi
        ///Traccia
        ///Macroforza
        ///Velenopunto
        ///Fuocodentro
        ///Magmascudo
        ///Idrovelo
        ///Magnetismo
        ///Antisuono
        ///Copripioggia
        ///Sabbiafiume
        ///Pressione
        ///Grassospe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Abilities_it {
            get {
                return ResourceManager.GetString("text_Abilities_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to なし
        ///あくしゅう
        ///あめふらし
        ///かそく
        ///カブトアーマー
        ///がんじょう
        ///しめりけ
        ///じゅうなん
        ///すながくれ
        ///せいでんき
        ///ちくでん
        ///ちょすい
        ///どんかん
        ///ノーてんき
        ///ふくがん
        ///ふみん
        ///へんしょく
        ///めんえき
        ///もらいび
        ///りんぷん
        ///マイペース
        ///きゅうばん
        ///いかく
        ///かげふみ
        ///さめはだ
        ///ふしぎなまもり
        ///ふゆう
        ///ほうし
        ///シンクロ
        ///クリアボディ
        ///しぜんかいふく
        ///ひらいしん
        ///てんのめぐみ
        ///すいすい
        ///ようりょくそ
        ///はっこう
        ///トレース
        ///ちからもち
        ///どくのトゲ
        ///せいしんりょく
        ///マグマのよろい
        ///みずのベール
        ///じりょく
        ///ぼうおん
        ///あめうけざら
        ///すなおこし
        ///プレッシャー
        ///あついしぼう
        ///はやおき
        ///ほのおのからだ
        ///にげあし
        ///するどいめ
        ///かいりきバサミ
        ///ものひろい
        ///なまけ
        ///はりきり
        ///メロメロボディ
        ///プラス
        ///マイナス
        ///てんきや
        ///ねんちゃく
        ///だっぴ
        ///こんじょう
        ///ふしぎなうろこ
        ///ヘドロえき
        ///しんりょく
        ///もうか
        ///げきりゅう
        ///むしのしらせ
        ///いしあたま
        ///ひでり
        ///ありじごく
        ///やるき
        ///しろいけむり
        ///ヨガパワー
        ///シェルアーマー
        ///エアロック
        ///ちどりあし
        ///でんきエンジン
        ///とうそうしん
        ///ふくつのこころ
        ///ゆきがくれ
        ///くいしんぼう
        ///いかりのつぼ
        ///かるわざ
        ///たいねつ
        ///たんじゅん
        ///かん [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Abilities_ja {
            get {
                return ResourceManager.GetString("text_Abilities_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 없음
        ///악취
        ///잔비
        ///가속
        ///전투무장
        ///옹골참
        ///습기
        ///유연
        ///모래숨기
        ///정전기
        ///축전
        ///저수
        ///둔감
        ///날씨부정
        ///복안
        ///불면
        ///변색
        ///면역
        ///타오르는불꽃
        ///인분
        ///마이페이스
        ///흡반
        ///위협
        ///그림자밟기
        ///까칠한피부
        ///불가사의부적
        ///부유
        ///포자
        ///싱크로
        ///클리어바디
        ///자연회복
        ///피뢰침
        ///하늘의은총
        ///쓱쓱
        ///엽록소
        ///발광
        ///트레이스
        ///천하장사
        ///독가시
        ///정신력
        ///마그마의무장
        ///수의베일
        ///자력
        ///방음
        ///젖은접시
        ///모래날림
        ///프레셔
        ///두꺼운지방
        ///일찍기상
        ///불꽃몸
        ///도주
        ///날카로운눈
        ///괴력집게
        ///픽업
        ///게으름
        ///의욕
        ///헤롱헤롱바디
        ///플러스
        ///마이너스
        ///기분파
        ///점착
        ///탈피
        ///근성
        ///이상한비늘
        ///해감액
        ///심록
        ///맹화
        ///급류
        ///벌레의알림
        ///돌머리
        ///가뭄
        ///개미지옥
        ///의기양양
        ///하얀연기
        ///순수한힘
        ///조가비갑옷
        ///에어록
        ///갈지자걸음
        ///전기엔진
        ///투쟁심
        ///불굴의마음
        ///눈숨기
        ///먹보
        ///분노의경혈
        ///곡예
        ///내열
        ///단순
        ///건조피부
        ///다운로드
        ///철주먹
        ///포이즌힐
        ///적응력
        ///스킬링크
        ///촉촉바디
        ///선파워
        ///속보
        ///노말스킨
        ///스나이퍼
        ///매직가드
        ///노가드
        ///시간벌기
        ///테크니션
        ///리프가드
        ///서투름
        ///틀깨기
        ///대운
        ///유폭
        ///위험예지
        ///예지몽
        ///천진
        ///색안경
        ///필터
        ///슬로스타트
        ///배짱
        ///마중물
        ///아이스바디
        ///하드록
        ///눈퍼뜨리기
        ///꿀모으기
        ///통찰
        ///이 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Abilities_ko {
            get {
                return ResourceManager.GetString("text_Abilities_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///eo
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///Normal
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///Pflanzen
        ///Pflanzen
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///Wolken
        ///Westliches Meer
        ///Westliches Meer
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Forms_de {
            get {
                return ResourceManager.GetString("text_Forms_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///Normal
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///Normal
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///Plant
        ///Plant
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///Overcast 
        ///West Sea
        ///West Sea
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Forms_en {
            get {
                return ResourceManager.GetString("text_Forms_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///a de Cast
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///a Normal
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///Planta
        ///Planta
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///a Encapotado
        ///Mar Oeste
        ///Mar Oeste
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Forms_es {
            get {
                return ResourceManager.GetString("text_Forms_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///e de Morphéo
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///e Normale
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///Plante
        ///Plante
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///Temps Couvert
        ///Mer Occident
        ///Mer Occident
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Forms_fr {
            get {
                return ResourceManager.GetString("text_Forms_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///a Cast
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///a Normale
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///Pianta
        ///Pianta
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///a Nuvola
        ///Mare Ovest
        ///Mare Ovest
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Forms_it {
            get {
                return ResourceManager.GetString("text_Forms_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///あるすがた
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///ポワルンのすがた
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///ノーマルフォルム
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///くさきのミノ
        ///くさきのミノ
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///ネガフォルム
        ///にしのうみ
        ///にしのうみ
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Forms_ja {
            get {
                return ResourceManager.GetString("text_Forms_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///형태별 모습
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///캐스퐁의 모습
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///노말폼
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///초목도롱
        ///초목도롱
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///네거폼
        ///서쪽바다
        ///서쪽바다
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Forms_ko {
            get {
                return ResourceManager.GetString("text_Forms_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Nichts)
        ///Meisterball
        ///Hyperball
        ///Superball
        ///Pokéball
        ///Safariball
        ///Netzball
        ///Tauchball
        ///Nestball
        ///Wiederball
        ///Timerball
        ///Luxusball
        ///Premierball
        ///Finsterball
        ///Heilball
        ///Flottball
        ///Jubelball
        ///Trank
        ///Gegengift
        ///Feuerheiler
        ///Eisheiler
        ///Aufwecker
        ///Para-Heiler
        ///Top-Genesung
        ///Top-Trank
        ///Hypertrank
        ///Supertrank
        ///Hyperheiler
        ///Beleber
        ///Top-Beleber
        ///Tafelwasser
        ///Sprudel
        ///Limonade
        ///Kuhmuh-Milch
        ///Energiestaub
        ///Kraftwurzel
        ///Heilpuder
        ///Vitalkraut
        ///Äther
        ///Top-Äther
        ///Elixier
        ///Top-Elixier
        ///Lavakeks
        ///Beerensaft
        ///Zauberasche
        ///KP-Plus
        ///Protein
        ///Eisen
        ///Carbon
        ///Kalzium
        ///Sonderbon [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Items_de {
            get {
                return ResourceManager.GetString("text_Items_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (None)
        ///Master Ball
        ///Ultra Ball
        ///Great Ball
        ///Poké Ball
        ///Safari Ball
        ///Net Ball
        ///Dive Ball
        ///Nest Ball
        ///Repeat Ball
        ///Timer Ball
        ///Luxury Ball
        ///Premier Ball
        ///Dusk Ball
        ///Heal Ball
        ///Quick Ball
        ///Cherish Ball
        ///Potion
        ///Antidote
        ///Burn Heal
        ///Ice Heal
        ///Awakening
        ///Paralyze Heal
        ///Full Restore
        ///Max Potion
        ///Hyper Potion
        ///Super Potion
        ///Full Heal
        ///Revive
        ///Max Revive
        ///Fresh Water
        ///Soda Pop
        ///Lemonade
        ///Moomoo Milk
        ///Energy Powder
        ///Energy Root
        ///Heal Powder
        ///Revival Herb
        ///Ether
        ///Max Ether
        ///Elixir
        ///Max Elixir
        ///Lava Cookie
        ///Berry Juice
        ///Sacred Ash
        ///HP Up
        ///Protein
        ///Iron
        ///Carbos
        ///Cal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Items_en {
            get {
                return ResourceManager.GetString("text_Items_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Ninguno)
        ///Master Ball
        ///Ultra Ball
        ///Super Ball
        ///Poké Ball
        ///Safari Ball
        ///Malla Ball
        ///Buceo Ball
        ///Nido Ball
        ///Acopio Ball
        ///Turno Ball
        ///Lujo Ball
        ///Honor Ball
        ///Ocaso Ball
        ///Sana Ball
        ///Veloz Ball
        ///Gloria Ball
        ///Poción
        ///Antídoto
        ///Antiquemar
        ///Antihielo
        ///Despertar
        ///Antiparalizador
        ///Restaurar Todo
        ///Poción Máxima
        ///Hiperpoción
        ///Superpoción
        ///Cura Total
        ///Revivir
        ///Revivir Máximo
        ///Agua Fresca
        ///Refresco
        ///Limonada
        ///Leche Mu-mu
        ///Polvo Energía
        ///Raíz Energía
        ///Polvo Curación
        ///Hierba Revivir
        ///Éter
        ///Éter Máximo
        ///Elixir
        ///Elixir Máximo
        ///Galleta Lava
        ///Zumo de Baya
        ///Ceniza Sagrad [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Items_es {
            get {
                return ResourceManager.GetString("text_Items_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Aucun)
        ///Master Ball
        ///Hyper Ball
        ///Super Ball
        ///Poké Ball
        ///Safari Ball
        ///Filet Ball
        ///Scuba Ball
        ///Faiblo Ball
        ///Bis Ball
        ///Chrono Ball
        ///Luxe Ball
        ///Honor Ball
        ///Sombre Ball
        ///Soin Ball
        ///Rapide Ball
        ///Mémoire Ball
        ///Potion
        ///Antidote
        ///Anti-Brûle
        ///Antigel
        ///Réveil
        ///Anti-Para
        ///Guérison
        ///Potion Max
        ///Hyper Potion
        ///Super Potion
        ///Total Soin
        ///Rappel
        ///Rappel Max
        ///Eau Fraîche
        ///Soda Cool
        ///Limonade
        ///Lait Meumeu
        ///Poudrénergie
        ///Racinénergie
        ///Poudre Soin
        ///Herbe Rappel
        ///Huile
        ///Huile Max
        ///Élixir
        ///Max Élixir
        ///Lava Cookie
        ///Jus de Baie
        ///Cendre Sacrée
        ///PV Plus
        ///Protéine
        ///Fer
        ///Carbone
        ///Cal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Items_fr {
            get {
                return ResourceManager.GetString("text_Items_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Niente)
        ///Master Ball
        ///Ultra Ball
        ///Mega Ball
        ///Poké Ball
        ///Safari Ball
        ///Rete Ball
        ///Sub Ball
        ///Minor Ball
        ///Bis Ball
        ///Timer Ball
        ///Chic Ball
        ///Premier Ball
        ///Scuro Ball
        ///Cura Ball
        ///Velox Ball
        ///Pregio Ball
        ///Pozione
        ///Antidoto
        ///Antiscottatura
        ///Antigelo
        ///Sveglia
        ///Antiparalisi
        ///Ricarica Totale
        ///Pozione Max
        ///Iperpozione
        ///Superpozione
        ///Cura Totale
        ///Revitalizzante
        ///Revitalizz. Max
        ///Acqua Fresca
        ///Gassosa
        ///Lemonsucco
        ///Latte Mumu
        ///Polvenergia
        ///Radicenergia
        ///Polvocura
        ///Vitalerba
        ///Etere
        ///Etere Max
        ///Elisir
        ///Elisir Max
        ///Lavottino
        ///Succodibacca
        ///Ceneremagica
        ///PS-Su
        ///Proteina
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Items_it {
            get {
                return ResourceManager.GetString("text_Items_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (なし)
        ///マスターボール
        ///ハイパーボール
        ///スーパーボール
        ///モンスターボール
        ///サファリボール
        ///ネットボール
        ///ダイブボール
        ///ネストボール
        ///リピートボール
        ///タイマーボール
        ///ゴージャスボール
        ///プレミアボール
        ///ダークボール
        ///ヒールボール
        ///クイックボール
        ///プレシャスボール
        ///キズぐすり
        ///どくけし
        ///やけどなおし
        ///こおりなおし
        ///ねむけざまし
        ///まひなおし
        ///かいふくのくすり
        ///まんたんのくすり
        ///すごいキズぐすり
        ///いいキズぐすり
        ///なんでもなおし
        ///げんきのかけら
        ///げんきのかたまり
        ///おいしいみず
        ///サイコソーダ
        ///ミックスオレ
        ///モーモーミルク
        ///ちからのこな
        ///ちからのねっこ
        ///ばんのうごな
        ///ふっかつそう
        ///ピーピーエイド
        ///ピーピーリカバー
        ///ピーピーエイダー
        ///ピーピーマックス
        ///フエンせんべい
        ///きのみジュース
        ///せいなるはい
        ///マックスアップ
        ///タウリン
        ///ブロムヘキシン
        ///インドメタシン
        ///リゾチウム
        ///ふしぎなアメ
        ///ポイントアップ
        ///キトサン
        ///ポイントマックス
        ///もりのヨウカン
        ///エフェクトガード
        ///クリティカット
        ///プラスパワー
        ///ディフェンダー
        ///スピーダー
        ///ヨクアタール
        ///スペシャルアップ
        ///スペシャルガード
        ///ピッピにんぎょう
        ///エネコのシッポ
        ///あおいビードロ
        ///きいろビードロ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Items_ja {
            get {
                return ResourceManager.GetString("text_Items_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (없음)
        ///마스터볼
        ///하이퍼볼
        ///수퍼볼
        ///몬스터볼
        ///사파리볼
        ///넷트볼
        ///다이브볼
        ///네스트볼
        ///리피드볼
        ///타이마볼
        ///럭셔리볼
        ///프레미어볼
        ///다크볼
        ///힐볼
        ///퀵볼
        ///프레셔스볼
        ///상처약
        ///해독제
        ///화상치료제
        ///얼음상태치료제
        ///잠깨는약
        ///마비치료제
        ///회복약
        ///풀회복약
        ///고급상처약
        ///좋은상처약
        ///만병통치제
        ///기력의조각
        ///기력의덩어리
        ///맛있는물
        ///미네랄사이다
        ///후르츠밀크
        ///튼튼밀크
        ///힘의가루
        ///힘의뿌리
        ///만능가루
        ///부활초
        ///피피에이드
        ///피피회복
        ///피피에이더
        ///피피맥스
        ///용암전병
        ///나무열매쥬스
        ///성스러운분말
        ///맥스업
        ///타우린
        ///사포닌
        ///알칼로이드
        ///리보플라빈
        ///이상한사탕
        ///포인트업
        ///키토산
        ///포인트맥스
        ///숲의양갱
        ///이펙트가드
        ///크리티컬커터
        ///플러스파워
        ///디펜드업
        ///스피드업
        ///잘-맞히기
        ///스페셜업
        ///스페셜가드
        ///삐삐인형
        ///에나비꼬리
        ///파랑비드로
        ///노랑비드로
        ///빨강비드로
        ///검정비드로
        ///하양비드로
        ///여울소금
        ///여울조개껍질
        ///빨강조각
        ///파랑조각
        ///노랑조각
        ///초록조각
        ///실버스프레이
        ///골드스프레이
        ///동굴탈출로프
        ///벌레회피스프레이
        ///태양의돌
        ///달의돌
        ///불꽃의돌
        ///천둥의돌
        ///물의돌
        ///리프의돌
        ///작은버섯
        ///큰버섯
        ///진주
        ///큰진주
        ///별의모래
        ///별의조각
        ///금구슬
        ///하트비늘
        ///달콤한꿀
        ///무럭무럭비료
        ///축축 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Items_ko {
            get {
                return ResourceManager.GetString("text_Items_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Nichts)
        ///Pfund
        ///Karateschlag
        ///Duplexhieb
        ///Kometenhieb
        ///Megahieb
        ///Zahltag
        ///Feuerschlag
        ///Eishieb
        ///Donnerschlag
        ///Kratzer
        ///Klammer
        ///Guillotine
        ///Klingensturm
        ///Schwerttanz
        ///Zerschneider
        ///Windstoß
        ///Flügelschlag
        ///Wirbelwind
        ///Fliegen
        ///Klammergriff
        ///Slam
        ///Rankenhieb
        ///Stampfer
        ///Doppelkick
        ///Megakick
        ///Sprungkick
        ///Fegekick
        ///Sandwirbel
        ///Kopfnuss
        ///Hornattacke
        ///Furienschlag
        ///Hornbohrer
        ///Tackle
        ///Bodyslam
        ///Wickel
        ///Bodycheck
        ///Fuchtler
        ///Risikotackle
        ///Rutenschlag
        ///Giftstachel
        ///Duonadel
        ///Nadelrakete
        ///Silberblick
        ///Biss
        ///Heuler
        ///Brüller
        ///Gesang
        ///Superschall
        ///Ultraschall
        ///Aussetze [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Moves_de {
            get {
                return ResourceManager.GetString("text_Moves_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (None)
        ///Pound
        ///Karate Chop
        ///Double Slap
        ///Comet Punch
        ///Mega Punch
        ///Pay Day
        ///Fire Punch
        ///Ice Punch
        ///Thunder Punch
        ///Scratch
        ///Vice Grip
        ///Guillotine
        ///Razor Wind
        ///Swords Dance
        ///Cut
        ///Gust
        ///Wing Attack
        ///Whirlwind
        ///Fly
        ///Bind
        ///Slam
        ///Vine Whip
        ///Stomp
        ///Double Kick
        ///Mega Kick
        ///Jump Kick
        ///Rolling Kick
        ///Sand Attack
        ///Headbutt
        ///Horn Attack
        ///Fury Attack
        ///Horn Drill
        ///Tackle
        ///Body Slam
        ///Wrap
        ///Take Down
        ///Thrash
        ///Double-Edge
        ///Tail Whip
        ///Poison Sting
        ///Twineedle
        ///Pin Missile
        ///Leer
        ///Bite
        ///Growl
        ///Roar
        ///Sing
        ///Supersonic
        ///Sonic Boom
        ///Disable
        ///Acid
        ///Ember
        ///Flamethrower
        ///Mist
        ///Water Gun
        ///Hyd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Moves_en {
            get {
                return ResourceManager.GetString("text_Moves_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Ninguno)
        ///Destructor
        ///Golpe Kárate
        ///Doble Bofetón
        ///Puño Cometa
        ///Megapuño
        ///Día de Pago
        ///Puño Fuego
        ///Puño Hielo
        ///Puño Trueno
        ///Arañazo
        ///Agarre
        ///Guillotina
        ///Viento Cortante
        ///Danza Espada
        ///Corte
        ///Tornado
        ///Ataque Ala
        ///Remolino
        ///Vuelo
        ///Atadura
        ///Atizar
        ///Látigo Cepa
        ///Pisotón
        ///Doble Patada
        ///Megapatada
        ///Patada Salto
        ///Patada Giro
        ///Ataque Arena
        ///Golpe Cabeza
        ///Cornada
        ///Ataque Furia
        ///Perforador
        ///Placaje
        ///Golpe Cuerpo
        ///Constricción
        ///Derribo
        ///Golpe
        ///Doble Filo
        ///Látigo
        ///Picotazo Ven
        ///Doble Ataque
        ///Pin Misil
        ///Malicioso
        ///Mordisco
        ///Gruñido
        ///Rugido
        ///Canto
        ///Supersónico
        ///Bomba  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Moves_es {
            get {
                return ResourceManager.GetString("text_Moves_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Aucun)
        ///Écras’Face
        ///Poing-Karaté
        ///Torgnoles
        ///Poing Comète
        ///Ultimapoing
        ///Jackpot
        ///Poing de Feu
        ///Poing-Glace
        ///Poing-Éclair
        ///Griffe
        ///Force Poigne
        ///Guillotine
        ///Coupe-Vent
        ///Danse-Lames
        ///Coupe
        ///Tornade
        ///Cru-Aile
        ///Cyclone
        ///Vol
        ///Étreinte
        ///Souplesse
        ///Fouet Lianes
        ///Écrasement
        ///Double Pied
        ///Ultimawashi
        ///Pied Sauté
        ///Mawashi Geri
        ///Jet de Sable
        ///Coup d’Boule
        ///Koud’Korne
        ///Furie
        ///Empal’Korne
        ///Charge
        ///Plaquage
        ///Ligotage
        ///Bélier
        ///Mania
        ///Damoclès
        ///Mimi-Queue
        ///Dard-Venin
        ///Double-Dard
        ///Dard-Nuée
        ///Groz’Yeux
        ///Morsure
        ///Rugissement
        ///Hurlement
        ///Berceuse
        ///Ultrason
        ///Sonicboom
        ///Entra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Moves_fr {
            get {
                return ResourceManager.GetString("text_Moves_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Niente)
        ///Botta
        ///Colpokarate
        ///Doppiasberla
        ///Cometapugno
        ///Megapugno
        ///Giornopaga
        ///Fuocopugno
        ///Gelopugno
        ///Tuonopugno
        ///Graffio
        ///Presa
        ///Ghigliottina
        ///Ventagliente
        ///Danzaspada
        ///Taglio
        ///Raffica
        ///Attacco d’Ala
        ///Turbine
        ///Volo
        ///Legatutto
        ///Schianto
        ///Frustata
        ///Pestone
        ///Doppiocalcio
        ///Megacalcio
        ///Calciosalto
        ///Calciorullo
        ///Turbosabbia
        ///Bottintesta
        ///Incornata
        ///Furia
        ///Perforcorno
        ///Azione
        ///Corposcontro
        ///Avvolgibotta
        ///Riduttore
        ///Colpo
        ///Sdoppiatore
        ///Colpocoda
        ///Velenospina
        ///Doppio Ago
        ///Missilspillo
        ///Fulmisguardo
        ///Morso
        ///Ruggito
        ///Boato
        ///Canto
        ///Supersuono
        ///Sonicboom
        ///Inibitore
        ///A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Moves_it {
            get {
                return ResourceManager.GetString("text_Moves_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (なし)
        ///はたく
        ///からてチョップ
        ///おうふくビンタ
        ///れんぞくパンチ
        ///メガトンパンチ
        ///ネコにこばん
        ///ほのおのパンチ
        ///れいとうパンチ
        ///かみなりパンチ
        ///ひっかく
        ///はさむ
        ///ハサミギロチン
        ///かまいたち
        ///つるぎのまい
        ///いあいぎり
        ///かぜおこし
        ///つばさでうつ
        ///ふきとばし
        ///そらをとぶ
        ///しめつける
        ///たたきつける
        ///つるのムチ
        ///ふみつけ
        ///にどげり
        ///メガトンキック
        ///とびげり
        ///まわしげり
        ///すなかけ
        ///ずつき
        ///つのでつく
        ///みだれづき
        ///つのドリル
        ///たいあたり
        ///のしかかり
        ///まきつく
        ///とっしん
        ///あばれる
        ///すてみタックル
        ///しっぽをふる
        ///どくばり
        ///ダブルニードル
        ///ミサイルばり
        ///にらみつける
        ///かみつく
        ///なきごえ
        ///ほえる
        ///うたう
        ///ちょうおんぱ
        ///ソニックブーム
        ///かなしばり
        ///ようかいえき
        ///ひのこ
        ///かえんほうしゃ
        ///しろいきり
        ///みずでっぽう
        ///ハイドロポンプ
        ///なみのり
        ///れいとうビーム
        ///ふぶき
        ///サイケこうせん
        ///バブルこうせん
        ///オーロラビーム
        ///はかいこうせん
        ///つつく
        ///ドリルくちばし
        ///じごくぐるま
        ///けたぐり
        ///カウンター
        ///ちきゅうなげ
        ///かいりき
        ///すいとる
        ///メガドレイン
        ///やどりぎのタネ
        ///せいちょう
        ///はっぱカッター
        ///ソーラービーム
        ///どくのこな
        ///しびれごな
        ///ねむりごな
        ///はなびらの [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Moves_ja {
            get {
                return ResourceManager.GetString("text_Moves_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (없음)
        ///막치기
        ///태권당수
        ///연속뺨치기
        ///연속펀치
        ///메가톤펀치
        ///고양이돈받기
        ///불꽃펀치
        ///냉동펀치
        ///번개펀치
        ///할퀴기
        ///찝기
        ///가위자르기
        ///칼바람
        ///칼춤
        ///풀베기
        ///바람일으키기
        ///날개치기
        ///날려버리기
        ///공중날기
        ///조이기
        ///힘껏치기
        ///덩굴채찍
        ///짓밟기
        ///두번치기
        ///메가톤킥
        ///점프킥
        ///돌려차기
        ///모래뿌리기
        ///박치기
        ///뿔찌르기
        ///마구찌르기
        ///뿔드릴
        ///몸통박치기
        ///누르기
        ///김밥말이
        ///돌진
        ///난동부리기
        ///이판사판태클
        ///꼬리흔들기
        ///독침
        ///더블니들
        ///바늘미사일
        ///째려보기
        ///물기
        ///울음소리
        ///울부짖기
        ///노래하기
        ///초음파
        ///소닉붐
        ///사슬묶기
        ///용해액
        ///불꽃세례
        ///화염방사
        ///흰안개
        ///물대포
        ///하이드로펌프
        ///파도타기
        ///냉동빔
        ///눈보라
        ///환상빔
        ///거품광선
        ///오로라빔
        ///파괴광선
        ///쪼기
        ///회전부리
        ///지옥의바퀴
        ///안다리걸기
        ///카운터
        ///지구던지기
        ///괴력
        ///흡수
        ///메가드레인
        ///씨뿌리기
        ///성장
        ///잎날가르기
        ///솔라빔
        ///독가루
        ///저리가루
        ///수면가루
        ///꽃잎댄스
        ///실뿜기
        ///용의분노
        ///회오리불꽃
        ///전기쇼크
        ///십만볼트
        ///전기자석파
        ///번개
        ///돌떨구기
        ///지진
        ///땅가르기
        ///구멍파기
        ///맹독
        ///염동력
        ///사이코키네시스
        ///최면술
        ///요가포즈
        ///고속이동
        ///전광석화
        ///분노
        ///순간이동
        ///나이트헤드
        ///흉내내기
        ///싫은소리
        ///그림자분신
        ///에이치피회복
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Moves_ko {
            get {
                return ResourceManager.GetString("text_Moves_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robust
        ///Solo
        ///Mutig
        ///Hart
        ///Frech
        ///Kühn
        ///Sanft
        ///Locker
        ///Pfiffig
        ///Lasch
        ///Scheu
        ///Hastig
        ///Ernst
        ///Froh
        ///Naiv
        ///Mäßig
        ///Mild
        ///Ruhig
        ///Zaghaft
        ///Hitzig
        ///Still
        ///Zart
        ///Forsch
        ///Sacht
        ///Kauzig.
        /// </summary>
        internal static string text_Natures_de {
            get {
                return ResourceManager.GetString("text_Natures_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardy
        ///Lonely
        ///Brave
        ///Adamant
        ///Naughty
        ///Bold
        ///Docile
        ///Relaxed
        ///Impish
        ///Lax
        ///Timid
        ///Hasty
        ///Serious
        ///Jolly
        ///Naive
        ///Modest
        ///Mild
        ///Quiet
        ///Bashful
        ///Rash
        ///Calm
        ///Gentle
        ///Sassy
        ///Careful
        ///Quirky.
        /// </summary>
        internal static string text_Natures_en {
            get {
                return ResourceManager.GetString("text_Natures_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuerte
        ///Huraño
        ///Audaz
        ///Firme
        ///Pícaro
        ///Osado
        ///Dócil
        ///Plácido
        ///Agitado
        ///Flojo
        ///Miedoso
        ///Activo
        ///Serio
        ///Alegre
        ///Ingenuo
        ///Modesto
        ///Afable
        ///Manso
        ///Tímido
        ///Alocado
        ///Sereno
        ///Amable
        ///Grosero
        ///Cauto
        ///Raro.
        /// </summary>
        internal static string text_Natures_es {
            get {
                return ResourceManager.GetString("text_Natures_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardi
        ///Solo
        ///Brave
        ///Rigide
        ///Mauvais
        ///Assuré
        ///Docile
        ///Relax
        ///Malin
        ///Lâche
        ///Timide
        ///Pressé
        ///Sérieux
        ///Jovial
        ///Naïf
        ///Modeste
        ///Doux
        ///Discret
        ///Pudique
        ///Foufou
        ///Calme
        ///Gentil
        ///Malpoli
        ///Prudent
        ///Bizarre.
        /// </summary>
        internal static string text_Natures_fr {
            get {
                return ResourceManager.GetString("text_Natures_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ardita
        ///Schiva
        ///Audace
        ///Decisa
        ///Birbona
        ///Sicura
        ///Docile
        ///Placida
        ///Scaltra
        ///Fiacca
        ///Timida
        ///Lesta
        ///Seria
        ///Allegra
        ///Ingenua
        ///Modesta
        ///Mite
        ///Quieta
        ///Ritrosa
        ///Ardente
        ///Calma
        ///Gentile
        ///Vivace
        ///Cauta
        ///Furba.
        /// </summary>
        internal static string text_Natures_it {
            get {
                return ResourceManager.GetString("text_Natures_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to がんばりや
        ///さみしがり
        ///ゆうかん
        ///いじっぱり
        ///やんちゃ
        ///ずぶとい
        ///すなお
        ///のんき
        ///わんぱく
        ///のうてんき
        ///おくびょう
        ///せっかち
        ///まじめ
        ///ようき
        ///むじゃき
        ///ひかえめ
        ///おっとり
        ///れいせい
        ///てれや
        ///うっかりや
        ///おだやか
        ///おとなしい
        ///なまいき
        ///しんちょう
        ///きまぐれ.
        /// </summary>
        internal static string text_Natures_ja {
            get {
                return ResourceManager.GetString("text_Natures_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 노력
        ///외로움
        ///용감
        ///고집
        ///개구쟁이
        ///대담
        ///온순
        ///무사태평
        ///장난꾸러기
        ///촐랑
        ///겁쟁이
        ///성급
        ///성실
        ///명랑
        ///천진난만
        ///조심
        ///의젓
        ///냉정
        ///수줍음
        ///덜렁
        ///차분
        ///얌전
        ///건방
        ///신중
        ///변덕.
        /// </summary>
        internal static string text_Natures_ko {
            get {
                return ResourceManager.GetString("text_Natures_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ei
        ///Bisasam
        ///Bisaknosp
        ///Bisaflor
        ///Glumanda
        ///Glutexo
        ///Glurak
        ///Schiggy
        ///Schillok
        ///Turtok
        ///Raupy
        ///Safcon
        ///Smettbo
        ///Hornliu
        ///Kokuna
        ///Bibor
        ///Taubsi
        ///Tauboga
        ///Tauboss
        ///Rattfratz
        ///Rattikarl
        ///Habitak
        ///Ibitak
        ///Rettan
        ///Arbok
        ///Pikachu
        ///Raichu
        ///Sandan
        ///Sandamer
        ///Nidoran♀
        ///Nidorina
        ///Nidoqueen
        ///Nidoran♂
        ///Nidorino
        ///Nidoking
        ///Piepi
        ///Pixi
        ///Vulpix
        ///Vulnona
        ///Pummeluff
        ///Knuddeluff
        ///Zubat
        ///Golbat
        ///Myrapla
        ///Duflor
        ///Giflor
        ///Paras
        ///Parasek
        ///Bluzuk
        ///Omot
        ///Digda
        ///Digdri
        ///Mauzi
        ///Snobilikat
        ///Enton
        ///Entoron
        ///Menki
        ///Rasaff
        ///Fukano
        ///Arkani
        ///Quapsel
        ///Quaputzi
        ///Quappo
        ///Abra
        ///Kadabra
        ///Simsala
        ///Machollo
        ///Ma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Species_de {
            get {
                return ResourceManager.GetString("text_Species_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egg
        ///Bulbasaur
        ///Ivysaur
        ///Venusaur
        ///Charmander
        ///Charmeleon
        ///Charizard
        ///Squirtle
        ///Wartortle
        ///Blastoise
        ///Caterpie
        ///Metapod
        ///Butterfree
        ///Weedle
        ///Kakuna
        ///Beedrill
        ///Pidgey
        ///Pidgeotto
        ///Pidgeot
        ///Rattata
        ///Raticate
        ///Spearow
        ///Fearow
        ///Ekans
        ///Arbok
        ///Pikachu
        ///Raichu
        ///Sandshrew
        ///Sandslash
        ///Nidoran♀
        ///Nidorina
        ///Nidoqueen
        ///Nidoran♂
        ///Nidorino
        ///Nidoking
        ///Clefairy
        ///Clefable
        ///Vulpix
        ///Ninetales
        ///Jigglypuff
        ///Wigglytuff
        ///Zubat
        ///Golbat
        ///Oddish
        ///Gloom
        ///Vileplume
        ///Paras
        ///Parasect
        ///Venonat
        ///Venomoth
        ///Diglett
        ///Dugtrio
        ///Meowth
        ///Persian
        ///Psyduck
        ///Golduck
        ///Mankey
        ///Primeape
        ///Growlithe
        ///Arcanine
        ///Pol [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Species_en {
            get {
                return ResourceManager.GetString("text_Species_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huevo
        ///Bulbasaur
        ///Ivysaur
        ///Venusaur
        ///Charmander
        ///Charmeleon
        ///Charizard
        ///Squirtle
        ///Wartortle
        ///Blastoise
        ///Caterpie
        ///Metapod
        ///Butterfree
        ///Weedle
        ///Kakuna
        ///Beedrill
        ///Pidgey
        ///Pidgeotto
        ///Pidgeot
        ///Rattata
        ///Raticate
        ///Spearow
        ///Fearow
        ///Ekans
        ///Arbok
        ///Pikachu
        ///Raichu
        ///Sandshrew
        ///Sandslash
        ///Nidoran♀
        ///Nidorina
        ///Nidoqueen
        ///Nidoran♂
        ///Nidorino
        ///Nidoking
        ///Clefairy
        ///Clefable
        ///Vulpix
        ///Ninetales
        ///Jigglypuff
        ///Wigglytuff
        ///Zubat
        ///Golbat
        ///Oddish
        ///Gloom
        ///Vileplume
        ///Paras
        ///Parasect
        ///Venonat
        ///Venomoth
        ///Diglett
        ///Dugtrio
        ///Meowth
        ///Persian
        ///Psyduck
        ///Golduck
        ///Mankey
        ///Primeape
        ///Growlithe
        ///Arcanine
        ///P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Species_es {
            get {
                return ResourceManager.GetString("text_Species_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Œuf
        ///Bulbizarre
        ///Herbizarre
        ///Florizarre
        ///Salamèche
        ///Reptincel
        ///Dracaufeu
        ///Carapuce
        ///Carabaffe
        ///Tortank
        ///Chenipan
        ///Chrysacier
        ///Papilusion
        ///Aspicot
        ///Coconfort
        ///Dardargnan
        ///Roucool
        ///Roucoups
        ///Roucarnage
        ///Rattata
        ///Rattatac
        ///Piafabec
        ///Rapasdepic
        ///Abo
        ///Arbok
        ///Pikachu
        ///Raichu
        ///Sabelette
        ///Sablaireau
        ///Nidoran♀
        ///Nidorina
        ///Nidoqueen
        ///Nidoran♂
        ///Nidorino
        ///Nidoking
        ///Mélofée
        ///Mélodelfe
        ///Goupix
        ///Feunard
        ///Rondoudou
        ///Grodoudou
        ///Nosferapti
        ///Nosferalto
        ///Mystherbe
        ///Ortide
        ///Rafflesia
        ///Paras
        ///Parasect
        ///Mimitoss
        ///Aéromite
        ///Taupiqueur
        ///Triopikeur
        ///Miaouss
        ///Persian
        ///Psykokwak
        ///Akwakwak
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Species_fr {
            get {
                return ResourceManager.GetString("text_Species_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uovo
        ///Bulbasaur
        ///Ivysaur
        ///Venusaur
        ///Charmander
        ///Charmeleon
        ///Charizard
        ///Squirtle
        ///Wartortle
        ///Blastoise
        ///Caterpie
        ///Metapod
        ///Butterfree
        ///Weedle
        ///Kakuna
        ///Beedrill
        ///Pidgey
        ///Pidgeotto
        ///Pidgeot
        ///Rattata
        ///Raticate
        ///Spearow
        ///Fearow
        ///Ekans
        ///Arbok
        ///Pikachu
        ///Raichu
        ///Sandshrew
        ///Sandslash
        ///Nidoran♀
        ///Nidorina
        ///Nidoqueen
        ///Nidoran♂
        ///Nidorino
        ///Nidoking
        ///Clefairy
        ///Clefable
        ///Vulpix
        ///Ninetales
        ///Jigglypuff
        ///Wigglytuff
        ///Zubat
        ///Golbat
        ///Oddish
        ///Gloom
        ///Vileplume
        ///Paras
        ///Parasect
        ///Venonat
        ///Venomoth
        ///Diglett
        ///Dugtrio
        ///Meowth
        ///Persian
        ///Psyduck
        ///Golduck
        ///Mankey
        ///Primeape
        ///Growlithe
        ///Arcanine
        ///Po [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Species_it {
            get {
                return ResourceManager.GetString("text_Species_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タマゴ
        ///フシギダネ
        ///フシギソウ
        ///フシギバナ
        ///ヒトカゲ
        ///リザード
        ///リザードン
        ///ゼニガメ
        ///カメール
        ///カメックス
        ///キャタピー
        ///トランセル
        ///バタフリー
        ///ビードル
        ///コクーン
        ///スピアー
        ///ポッポ
        ///ピジョン
        ///ピジョット
        ///コラッタ
        ///ラッタ
        ///オニスズメ
        ///オニドリル
        ///アーボ
        ///アーボック
        ///ピカチュウ
        ///ライチュウ
        ///サンド
        ///サンドパン
        ///ニドラン♀
        ///ニドリーナ
        ///ニドクイン
        ///ニドラン♂
        ///ニドリーノ
        ///ニドキング
        ///ピッピ
        ///ピクシー
        ///ロコン
        ///キュウコン
        ///プリン
        ///プクリン
        ///ズバット
        ///ゴルバット
        ///ナゾノクサ
        ///クサイハナ
        ///ラフレシア
        ///パラス
        ///パラセクト
        ///コンパン
        ///モルフォン
        ///ディグダ
        ///ダグトリオ
        ///ニャース
        ///ペルシアン
        ///コダック
        ///ゴルダック
        ///マンキー
        ///オコリザル
        ///ガーディ
        ///ウインディ
        ///ニョロモ
        ///ニョロゾ
        ///ニョロボン
        ///ケーシィ
        ///ユンゲラー
        ///フーディン
        ///ワンリキー
        ///ゴーリキー
        ///カイリキー
        ///マダツボミ
        ///ウツドン
        ///ウツボット
        ///メノクラゲ
        ///ドククラゲ
        ///イシツブテ
        ///ゴローン
        ///ゴローニャ
        ///ポニータ
        ///ギャロップ
        ///ヤドン
        ///ヤドラン
        ///コイル
        ///レアコイル
        ///カモネギ
        ///ドードー
        ///ドードリオ
        ///パウワウ
        ///ジュゴン
        ///ベトベター
        ///ベトベトン
        ///シェルダー
        ///パルシェン
        ///ゴース
        ///ゴースト
        ///ゲン [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Species_ja {
            get {
                return ResourceManager.GetString("text_Species_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 알
        ///이상해씨
        ///이상해풀
        ///이상해꽃
        ///파이리
        ///리자드
        ///리자몽
        ///꼬부기
        ///어니부기
        ///거북왕
        ///캐터피
        ///단데기
        ///버터플
        ///뿔충이
        ///딱충이
        ///독침붕
        ///구구
        ///피죤
        ///피죤투
        ///꼬렛
        ///레트라
        ///깨비참
        ///깨비드릴조
        ///아보
        ///아보크
        ///피카츄
        ///라이츄
        ///모래두지
        ///고지
        ///니드런♀
        ///니드리나
        ///니드퀸
        ///니드런♂
        ///니드리노
        ///니드킹
        ///삐삐
        ///픽시
        ///식스테일
        ///나인테일
        ///푸린
        ///푸크린
        ///주뱃
        ///골뱃
        ///뚜벅쵸
        ///냄새꼬
        ///라플레시아
        ///파라스
        ///파라섹트
        ///콘팡
        ///도나리
        ///디그다
        ///닥트리오
        ///나옹
        ///페르시온
        ///고라파덕
        ///골덕
        ///망키
        ///성원숭
        ///가디
        ///윈디
        ///발챙이
        ///슈륙챙이
        ///강챙이
        ///캐이시
        ///윤겔라
        ///후딘
        ///알통몬
        ///근육몬
        ///괴력몬
        ///모다피
        ///우츠동
        ///우츠보트
        ///왕눈해
        ///독파리
        ///꼬마돌
        ///데구리
        ///딱구리
        ///포니타
        ///날쌩마
        ///야돈
        ///야도란
        ///코일
        ///레어코일
        ///파오리
        ///두두
        ///두트리오
        ///쥬쥬
        ///쥬레곤
        ///질퍽이
        ///질뻐기
        ///셀러
        ///파르셀
        ///고오스
        ///고우스트
        ///팬텀
        ///롱스톤
        ///슬리프
        ///슬리퍼
        ///크랩
        ///킹크랩
        ///찌리리공
        ///붐볼
        ///아라리
        ///나시
        ///탕구리
        ///텅구리
        ///시라소몬
        ///홍수몬
        ///내루미
        ///또가스
        ///또도가스
        ///뿔카노
        ///코뿌리
        ///럭키
        ///덩쿠리
        ///캥카
        ///쏘드라
        ///시드라
        ///콘치
        ///왕콘치
        ///별가사리
        ///아쿠스타
        ///마임맨
        ///스라크
        ///루주라
        ///에레브
        ///마그마
        ///쁘사이저
        ///켄 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Species_ko {
            get {
                return ResourceManager.GetString("text_Species_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal
        ///Kampf
        ///Flug
        ///Gift
        ///Boden
        ///Gestein
        ///Käfer
        ///Geist
        ///Stahl
        ///Feuer
        ///Wasser
        ///Pflanze
        ///Elektro
        ///Psycho
        ///Eis
        ///Drache
        ///Unlicht
        ///Fee.
        /// </summary>
        internal static string text_Types_de {
            get {
                return ResourceManager.GetString("text_Types_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal
        ///Fighting
        ///Flying
        ///Poison
        ///Ground
        ///Rock
        ///Bug
        ///Ghost
        ///Steel
        ///Fire
        ///Water
        ///Grass
        ///Electric
        ///Psychic
        ///Ice
        ///Dragon
        ///Dark
        ///Fairy.
        /// </summary>
        internal static string text_Types_en {
            get {
                return ResourceManager.GetString("text_Types_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal
        ///Lucha
        ///Volador
        ///Veneno
        ///Tierra
        ///Roca
        ///Bicho
        ///Fantasma
        ///Acero
        ///Fuego
        ///Agua
        ///Planta
        ///Eléctrico
        ///Psíquico
        ///Hielo
        ///Dragón
        ///Siniestro
        ///Hada.
        /// </summary>
        internal static string text_Types_es {
            get {
                return ResourceManager.GetString("text_Types_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal
        ///Combat
        ///Vol
        ///Poison
        ///Sol
        ///Roche
        ///Insecte
        ///Spectre
        ///Acier
        ///Feu
        ///Eau
        ///Plante
        ///Électrik
        ///Psy
        ///Glace
        ///Dragon
        ///Ténèbres
        ///Fée.
        /// </summary>
        internal static string text_Types_fr {
            get {
                return ResourceManager.GetString("text_Types_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normale
        ///Lotta
        ///Volante
        ///Veleno
        ///Terra
        ///Roccia
        ///Coleottero
        ///Spettro
        ///Acciaio
        ///Fuoco
        ///Acqua
        ///Erba
        ///Elettro
        ///Psico
        ///Ghiaccio
        ///Drago
        ///Buio
        ///Folletto.
        /// </summary>
        internal static string text_Types_it {
            get {
                return ResourceManager.GetString("text_Types_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ノーマル
        ///かくとう
        ///ひこう
        ///どく
        ///じめん
        ///いわ
        ///むし
        ///ゴースト
        ///はがね
        ///ほのお
        ///みず
        ///くさ
        ///でんき
        ///エスパー
        ///こおり
        ///ドラゴン
        ///あく
        ///フェアリー.
        /// </summary>
        internal static string text_Types_ja {
            get {
                return ResourceManager.GetString("text_Types_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 노말
        ///격투
        ///비행
        ///독
        ///땅
        ///바위
        ///벌레
        ///고스트
        ///강철
        ///불꽃
        ///물
        ///풀
        ///전기
        ///에스퍼
        ///얼음
        ///드래곤
        ///악
        ///페어리.
        /// </summary>
        internal static string text_Types_ko {
            get {
                return ResourceManager.GetString("text_Types_ko", resourceCulture);
            }
        }
    }
}
